export enum PermisoEnum {
  // USUARIOS
  VER_USUARIOS = 'VER_USUARIOS',
  CREAR_USUARIOS = 'CREAR_USUARIOS',
  EDITAR_USUARIOS = 'EDITAR_USUARIOS',
  ELIMINAR_USUARIOS = 'ELIMINAR_USUARIOS',
  ASIGNAR_ROLES = 'ASIGNAR_ROLES',

  // ROLES Y PERMISOS
  GESTIONAR_ROLES = 'GESTIONAR_ROLES',
  VER_ROLES = 'VER_ROLES',
  ASIGNAR_PERMISOS_INDIVIDUALES = 'ASIGNAR_PERMISOS_INDIVIDUALES',
  REVOCAR_PERMISOS_INDIVIDUALES = 'REVOCAR_PERMISOS_INDIVIDUALES',

  // CITAS
  VER_CITAS = 'VER_CITAS',
  CREAR_CITAS = 'CREAR_CITAS',
  EDITAR_CITAS = 'EDITAR_CITAS',
  CANCELAR_CITAS = 'CANCELAR_CITAS',
  VER_TODAS_LAS_CITAS = 'VER_TODAS_LAS_CITAS',

  // TRATAMIENTOS
  VER_TRATAMIENTOS = 'VER_TRATAMIENTOS',
  CREAR_TRATAMIENTOS = 'CREAR_TRATAMIENTOS',
  EDITAR_TRATAMIENTOS = 'EDITAR_TRATAMIENTOS',
  APROBAR_TRATAMIENTOS = 'APROBAR_TRATAMIENTOS',
  VER_TODOS_TRATAMIENTOS = 'VER_TODOS_TRATAMIENTOS',

  // PACIENTES
  VER_PACIENTES = 'VER_PACIENTES',
  CREAR_PACIENTES = 'CREAR_PACIENTES',
  EDITAR_PACIENTES = 'EDITAR_PACIENTES',

  // SOLICITUDES
  CREAR_SOLICITUDES = 'CREAR_SOLICITUDES',
  VER_SOLICITUDES = 'VER_SOLICITUDES',
  APROBAR_SOLICITUDES = 'APROBAR_SOLICITUDES',

  // ESPECIALIDADES
  VER_ESPECIALIDADES = 'VER_ESPECIALIDADES',
  GESTIONAR_ESPECIALIDADES = 'GESTIONAR_ESPECIALIDADES',

  // ENCUESTAS DE TAMIZAJE
  VER_ENCUESTAS = 'VER_ENCUESTAS',
  CREAR_ENCUESTAS = 'CREAR_ENCUESTAS',
  VER_ESTADISTICAS = 'VER_ESTADISTICAS',
  VER_CONFIGURACION = 'VER_CONFIGURACION',

  // ARCHIVOS
  VER_ARCHIVOS = 'VER_ARCHIVOS',
  SUBIR_ARCHIVOS = 'SUBIR_ARCHIVOS',
  DESCARGAR_ARCHIVOS = 'DESCARGAR_ARCHIVOS',
}

export const PERMISOS_POR_MODULO = {
  USUARIOS: [
    PermisoEnum.VER_USUARIOS,
    PermisoEnum.CREAR_USUARIOS,
    PermisoEnum.EDITAR_USUARIOS,
    PermisoEnum.ELIMINAR_USUARIOS,
    PermisoEnum.ASIGNAR_ROLES,
  ],
  ROLES_PERMISOS: [
    PermisoEnum.GESTIONAR_ROLES,
    PermisoEnum.VER_ROLES,
    PermisoEnum.ASIGNAR_PERMISOS_INDIVIDUALES,
    PermisoEnum.REVOCAR_PERMISOS_INDIVIDUALES,
  ],
  CITAS: [
    PermisoEnum.VER_CITAS,
    PermisoEnum.CREAR_CITAS,
    PermisoEnum.EDITAR_CITAS,
    PermisoEnum.CANCELAR_CITAS,
    PermisoEnum.VER_TODAS_LAS_CITAS,
  ],
  TRATAMIENTOS: [
    PermisoEnum.VER_TRATAMIENTOS,
    PermisoEnum.CREAR_TRATAMIENTOS,
    PermisoEnum.EDITAR_TRATAMIENTOS,
    PermisoEnum.APROBAR_TRATAMIENTOS,
    PermisoEnum.VER_TODOS_TRATAMIENTOS,
  ],
  PACIENTES: [
    PermisoEnum.VER_PACIENTES,
    PermisoEnum.CREAR_PACIENTES,
    PermisoEnum.EDITAR_PACIENTES,
  ],
  SOLICITUDES: [
    PermisoEnum.CREAR_SOLICITUDES,
    PermisoEnum.VER_SOLICITUDES,
    PermisoEnum.APROBAR_SOLICITUDES,
  ],
  ESPECIALIDADES: [
    PermisoEnum.VER_ESPECIALIDADES,
    PermisoEnum.GESTIONAR_ESPECIALIDADES,
  ],
  ENCUESTAS: [
    PermisoEnum.VER_ENCUESTAS,
    PermisoEnum.CREAR_ENCUESTAS,
    PermisoEnum.VER_ESTADISTICAS,
    PermisoEnum.VER_CONFIGURACION,
  ],
  ARCHIVOS: [
    PermisoEnum.VER_ARCHIVOS,
    PermisoEnum.SUBIR_ARCHIVOS,
    PermisoEnum.DESCARGAR_ARCHIVOS,
  ],
};